insert into items(name, description, price) values('Laptop', 'Compact electronic computer', 80000.00);
insert into items(name, description, price) values('Smartphone', 'Samsung latest Smart phone', 22500.00);
insert into items(name, description, price) values('Cookies', 'Biskfarm cookies & snacks', 125.50);
insert into items(name, description, price) values('Cold-drinks','Coca-cola cold drinks', 99.79);
insert into items(name, description, price) values('Rice', '10Kg rice bag from Ganesh', 550.00);
insert into items(name, description, price) values('Washing-Machine', 'BOSCH heavy duty washing machine (Front load)', 35378.56);
insert into items(name, description, price) values('QLED-TV', 'Samsung NEO QLED TV', 278586.89);
insert into items(name, description, price) values('Trousers(M)', 'Trousers for Men', 999.00);
insert into items(name, description, price) values('Trousers(F)', 'Trousers for women', 999.00);
insert into items(name, description, price) values('iPhone-X', 'iPhone 10 from Apple Inc., 128GB', 79999.00);
insert into items(name, description, price) values('Macbook Pro', 'Latest Macbook from Apple Inc. Pro version', 250000.00);
insert into items(name, description, price) values('Shampoo', 'Sunsilk shampoo from HU LTD. 450ml', 349.00);
insert into items(name, description, price) values('T-shirt', 'T-shirts for men', 500.00);
insert into items(name, description, price) values('Camera', 'DSLR camera from Sony', 85000.00);
